apiVersion: v1
kind: Endpoints
metadata:
  name: sonarqube
subsets:
  - addresses:
      - ip: 172.17.108.43  # Usa la IP de tu WSL (verificada con `ip addr show eth0`)
    ports:
      - port: 9000

