export const getEnvVariables = () => {
    return {
        VITE_PORT_LOCAL: import.meta.env.VITE_PORT_LOCAL,
        /* VARIABLE DE ENTORNO PARA EL MICROSERVICIO  DESARROLLO */
        VITE_ENV_MS_BUSINESS_API_URL_DESARROLLO: import.meta.env.VITE_ENV_MS_BUSINESS_API_URL_DESARROLLO,
        VITE_ENV_MS_PYTHON_API_URL_DESARROLLO: import.meta.env.VITE_ENV_MS_PYTHON_API_URL_DESARROLLO,
        /* VARIABLE DE ENTORNO PARA EL MICROSERVICIO  PRODUCCION */
        VITE_ENV_MS_BUSINESS_API_URL_PRODUCCION: import.meta.env.VITE_ENV_MS_BUSINESS_API_URL_PRODUCCION,
        VITE_ENV_MS_PYTHON_API_URL_PRODUCCION: import.meta.env.VITE_ENV_MS_PYTHON_API_URL_PRODUCCION,
        /* ENTORNO DE DESARROLLO */
        VITE_ENTORNO: import.meta.env.VITE_ENTORNO,
    }
}

